### ISSUE TITLE
Error: no mixin named make-sm-column

### ISSUE THREAD

**Issue by Pater100** [Levdbas/BasePlateWP#1]
Hey Erik,

I had a problem with the new master,

When i start a new project i get immediately the error back from gulp about a missing file Globals.scss.

When I deleted that line in the main.scss i got the following error back from the terminal:

`Error: no mixin named make-sm-column

       Backtrace:
       	assets/styles/components/_grid.scss:3
        on line 3 of assets/styles/components/_grid.scss
>>   @include make-sm-column($main-sm-columns);
   -----------^

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: assets/styles/components/_grid.scss
Error: no mixin named make-sm-column

       Backtrace:
       	assets/styles/components/_grid.scss:3
        on line 3 of assets/styles/components/_grid.scss
>>   @include make-sm-column($main-sm-columns);`

I can't find any way to remove this error other then deleting all the lines in the grid.scss file.

Maybe you can find the problem and fix it for the next commit?

Thx in advance 👍

**Comment by Pater100** [comment]
Thx for clearing the first 2 things.

I have 2 others for you,

I have deleted the whole wp_classes.scss file, it gave another error ad compile.
Should i delete the whole file or do we need to change something?

next i had an compile error in the _forms.scss file. there need to be an !optional attribute at the end of line 14. (@extend .btn-default)

Thx for the fast fixes 👍

**Comment by Levdbas** [comment]
Hi @Pater100 , both should be fixed right now. Thanks for your input and good luck!
